#############################################################################
# Makefile for building: compiler.app/Contents/MacOS/compiler
# Generated by qmake (3.0) (Qt 5.1.1) on: Thu Oct 17 21:51:34 2013
# Project:  ../compiler/compiler.pro
# Template: app
# Command: /Applications/Qt/5.1.1/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile ../compiler/compiler.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options


MY_SRC			=	src_analex/AAutomata.cpp			\
					src_analex/NumberAutomata.cpp		\
					src_analex/IdAutomata.cpp			\
					src_analex/StringAutomata.cpp		\
					src_analex/ArithmeticAutomata.cpp	\
					src_analex/RelationalAutomata.cpp	\
					src_analex/AsignmentAutomata.cpp	\
					src_analex/PunctuationAutomata.cpp	\
					src_analex/AgrupationAutomata.cpp	\
					src_analex/OutputAutomata.cpp		\
					src_analex/ReservedAutomata.cpp	\
					src_analex/SymbolTable.cpp			\
					src_analex/Analex.cpp				\
					src_analex/main.cpp


CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_SENSORS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -I./include -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Applications/Qt/5.1.1/clang_64/mkspecs/macx-clang -Isrc/ -I/Applications/Qt/5.1.1/clang_64/include -I/Applications/Qt/5.1.1/clang_64/include/QtWebKitWidgets -I/Applications/Qt/5.1.1/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers -I/Applications/Qt/5.1.1/clang_64/include/QtQuick -I/Applications/Qt/5.1.1/clang_64/lib/QtQuick.framework/Versions/5/Headers -I/Applications/Qt/5.1.1/clang_64/include/QtOpenGL -I/Applications/Qt/5.1.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers -I/Applications/Qt/5.1.1/clang_64/include/QtPrintSupport -I/Applications/Qt/5.1.1/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers -I/Applications/Qt/5.1.1/clang_64/include/QtWebKit -I/Applications/Qt/5.1.1/clang_64/lib/QtWebKit.framework/Versions/5/Headers -I/Applications/Qt/5.1.1/clang_64/include/QtQml -I/Applications/Qt/5.1.1/clang_64/lib/QtQml.framework/Versions/5/Headers -I/Applications/Qt/5.1.1/clang_64/include/QtWidgets -I/Applications/Qt/5.1.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Applications/Qt/5.1.1/clang_64/include/QtNetwork -I/Applications/Qt/5.1.1/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I/Applications/Qt/5.1.1/clang_64/include/QtSensors -I/Applications/Qt/5.1.1/clang_64/lib/QtSensors.framework/Versions/5/Headers -I/Applications/Qt/5.1.1/clang_64/include/QtGui -I/Applications/Qt/5.1.1/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Applications/Qt/5.1.1/clang_64/include/QtCore -I/Applications/Qt/5.1.1/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I. -F/Applications/Qt/5.1.1/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Applications/Qt/5.1.1/clang_64/lib -framework QtWebKitWidgets -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework QtGui -framework QtOpenGL -framework QtWidgets -framework QtPrintSupport -framework Cocoa -framework QtWebKit -framework QtSql -framework QtSensors -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Applications/Qt/5.1.1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
MY_CXX		  = g++
MY_NAME	      = analex
MY_FILE_NAME  = symbolTable.txt

####### Output directory

OBJECTS_DIR   = ./
MY_OBJS	      = $(MY_SRC:.cpp=.o)

####### Files

SOURCES       = src/main.cpp \
				src/mainwindow.cpp \
				src/cuadruple.cpp moc_mainwindow.cpp
OBJECTS       = src/main.o \
		src/mainwindow.o \
		src/cuadruple.o \
		moc_mainwindow.o
DIST          = /Applications/Qt/5.1.1/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/lex.prf \
		src/compiler.pro \
		src/compiler.pro
QMAKE_TARGET  = compiler
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = compiler

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all:  Makefile compiler.app/Contents/PkgInfo compiler.app/Contents/Resources/empty.lproj compiler.app/Contents/Info.plist $(TARGET) 

$(MY_NAME):		$(MY_OBJS)
				$(MY_CXX) $(CXXFLAS) -o $@ $^

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d compiler.app/Contents/MacOS/ || mkdir -p compiler.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: src/compiler.pro /Applications/Qt/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt/5.1.1/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.1.1/clang_64/mkspecs/features/lex.prf \
		src/compiler.pro \
		/Applications/Qt/5.1.1/clang_64/lib/QtWebKitWidgets.framework/QtWebKitWidgets.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtQml.framework/QtQml.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtCore.framework/QtCore.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtWebKit.framework/QtWebKit.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtSql.framework/QtSql.prl \
		/Applications/Qt/5.1.1/clang_64/lib/QtSensors.framework/QtSensors.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile src/compiler.pro
/Applications/Qt/5.1.1/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/qdevice.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/common/shell-unix.conf:
/Applications/Qt/5.1.1/clang_64/mkspecs/common/unix.conf:
/Applications/Qt/5.1.1/clang_64/mkspecs/common/mac.conf:
/Applications/Qt/5.1.1/clang_64/mkspecs/common/macx.conf:
/Applications/Qt/5.1.1/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt/5.1.1/clang_64/mkspecs/common/clang.conf:
/Applications/Qt/5.1.1/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt/5.1.1/clang_64/mkspecs/qconfig.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/spec_post.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/qt.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/resources.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/moc.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/uic.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt/5.1.1/clang_64/mkspecs/features/lex.prf:
src/compiler.pro:
/Applications/Qt/5.1.1/clang_64/lib/QtWebKitWidgets.framework/QtWebKitWidgets.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtQml.framework/QtQml.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtCore.framework/QtCore.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtWebKit.framework/QtWebKit.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtSql.framework/QtSql.prl:
/Applications/Qt/5.1.1/clang_64/lib/QtSensors.framework/QtSensors.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile src/compiler.pro

qmake_all: FORCE

compiler.app/Contents/PkgInfo: 
	@test -d compiler.app/Contents || mkdir -p compiler.app/Contents
	@$(DEL_FILE) compiler.app/Contents/PkgInfo
	@echo "APPL????" >compiler.app/Contents/PkgInfo
compiler.app/Contents/Resources/empty.lproj: 
	@test -d compiler.app/Contents/Resources || mkdir -p compiler.app/Contents/Resources
	@touch compiler.app/Contents/Resources/empty.lproj
	
compiler.app/Contents/Info.plist: 
	@test -d compiler.app/Contents || mkdir -p compiler.app/Contents
	@$(DEL_FILE) compiler.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,compiler,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt/5.1.1/clang_64/mkspecs/macx-clang/Info.plist.app >compiler.app/Contents/Info.plist
dist: 
	@test -d .tmp/compiler1.0.0 || mkdir -p .tmp/compiler1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/compiler1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/cuadruple.h .tmp/compiler1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/cuadruple.cpp .tmp/compiler1.0.0/ && $(COPY_FILE) --parents src/mainwindow.ui .tmp/compiler1.0.0/ && (cd `dirname .tmp/compiler1.0.0` && $(TAR) compiler1.0.0.tar compiler1.0.0 && $(COMPRESS) compiler1.0.0.tar) && $(MOVE) `dirname .tmp/compiler1.0.0`/compiler1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/compiler1.0.0



clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core
	rm -f $(MY_OBJS)
	rm -f $(MY_NAME)
	rm -f $(MY_FILE_NAME)

####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r compiler.app
	-$(DEL_FILE) $(TARGET)
	#-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /Applications/Qt/5.1.1/clang_64/include/QtWidgets/QMainWindow \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qmainwindow.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qwidget.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qwindowdefs.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmutex.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qflags.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qwindowdefs_win.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobject.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstring.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qchar.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qlist.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmargins.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qrect.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsize.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qpoint.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpaintdevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpalette.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qcolor.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qrgb.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstringlist.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qdatastream.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qiodevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qpair.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qregexp.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstringmatcher.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qbrush.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qvector.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qmatrix.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpolygon.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qregion.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qline.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qtransform.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpainterpath.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qimage.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpixmap.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qshareddata.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qhash.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qfont.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qfontmetrics.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qfontinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qsizepolicy.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qcursor.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qkeysequence.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qevent.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qvariant.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmap.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qdebug.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtextstream.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qlocale.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qset.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcontiguouscache.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qurl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qurlquery.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qfile.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qfiledevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qvector2d.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qtouchdevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qtabwidget.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qicon.h \
		src/mainwindow.h
	/Applications/Qt/5.1.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) src/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: src/mainwindow.ui \
		/Applications/Qt/5.1.1/clang_64/include/QtWebKitWidgets/QWebView
	/Applications/Qt/5.1.1/clang_64/bin/uic src/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/QMainWindow \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qmainwindow.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qwidget.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qwindowdefs.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmutex.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qflags.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qwindowdefs_win.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobject.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstring.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qchar.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qlist.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmargins.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qrect.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsize.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qpoint.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpaintdevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpalette.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qcolor.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qrgb.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstringlist.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qdatastream.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qiodevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qpair.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qregexp.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstringmatcher.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qbrush.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qvector.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qmatrix.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpolygon.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qregion.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qline.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qtransform.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpainterpath.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qimage.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpixmap.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qshareddata.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qhash.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qfont.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qfontmetrics.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qfontinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qsizepolicy.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qcursor.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qkeysequence.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qevent.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qvariant.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmap.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qdebug.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtextstream.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qlocale.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qset.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcontiguouscache.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qurl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qurlquery.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qfile.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qfiledevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qvector2d.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qtouchdevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qtabwidget.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qicon.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/QApplication \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qapplication.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcoreapplication.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qeventloop.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qdesktopwidget.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qguiapplication.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/QMainWindow \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qmainwindow.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qwidget.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qwindowdefs.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmutex.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qflags.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qwindowdefs_win.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobject.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstring.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qchar.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qlist.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmargins.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qrect.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsize.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qpoint.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpaintdevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpalette.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qcolor.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qrgb.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstringlist.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qdatastream.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qiodevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qpair.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qregexp.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstringmatcher.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qbrush.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qvector.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qmatrix.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpolygon.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qregion.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qline.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qtransform.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpainterpath.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qimage.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qpixmap.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qshareddata.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qhash.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qfont.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qfontmetrics.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qfontinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qsizepolicy.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qcursor.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qkeysequence.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qevent.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qvariant.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmap.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qdebug.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtextstream.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qlocale.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qset.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcontiguouscache.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qurl.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qurlquery.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qfile.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qfiledevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qvector2d.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qtouchdevice.h \
		/Applications/Qt/5.1.1/clang_64/include/QtWidgets/qtabwidget.h \
		/Applications/Qt/5.1.1/clang_64/include/QtGui/qicon.h \
		ui_mainwindow.h \
		src/cuadruple.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/QString \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/QVector \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

cuadruple.o: src/cuadruple.cpp src/cuadruple.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/QString \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstring.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qchar.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qmutex.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qflags.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt/5.1.1/clang_64/include/QtCore/qstringbuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cuadruple.o src/cuadruple.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

